### ISSUE TITLE
lib/common/check_permissions() can error if macos using gnu stat

### ISSUE THREAD

**Issue by kr3cj** [rfocosi/otp-cli#6]
On macos, if `stat` resolves to a gnu version, this breaks the common library for otp-cli.

On my macos system, I override core utilities to use the GNU flavors instead of BSD flavors.  In particular, I install `coreutils` from homebrew and prioritize its path over the system path. This overrides the `stat` command to use the gnu version:

```sh
brew install coreutils
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
$ which stat
/usr/local/opt/coreutils/libexec/gnubin/stat
```

When I run any `otp-cli` command, it will check the permissions of any files in `~/.otp-cli/tokens`. But it uses the relative path of `stat` which picks up my gnu version:

```sh
$ otp-cli help
stat: cannot read file system information for '%A': No such file or directory
~/.homesick/repos/otp-cli/lib/common: line 50: [: too many arguments
Usage: otp-cli <command> [-h]

 -h : If after a <command>, the respective help. Otherwise, this help.

 Where <command> are:

 help   : This help
 add    : Add a new token
 clip   : Copy OTP to clipboard
 show   : Show the current OTP
 list   : List available tokens
 unlock : Unlock an encrypted token
 remove : Remove a token
```

To drill down to the exact problem, the gnu version of stat does not work with [line 42 of common](https://github.com/rfocosi/otp-cli/blob/15b85e18c639ad7b55c06eda1f59aba8b44b387c/lib/common#L42):

```sh
$ which stat
/usr/local/opt/coreutils/libexec/gnubin/stat

$ stat -L -f "%A" ~/otp-cli/tokens/example.enc
stat: cannot read file system information for '%A': No such file or directory
  File: "~/otp-cli/tokens/example.enc"
    ID: 100000400000019 Namelen: ?       Type: apfs
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 122086923  Free: 84514192   Available: 81211171
Inodes: Total: 4883476920 Free: 4882127831

# if I use the system's built-in, BSD version of stat, then all is well:
$ /usr/bin/stat -L -f "%A" ~/otp-cli/tokens/example.enc
400
```

This should be able to be fixed by using the absolute path of `/usr/bin/stat` on [line 42 of common](https://github.com/rfocosi/otp-cli/blob/15b85e18c639ad7b55c06eda1f59aba8b44b387c/lib/common#L42).

**Comment by rfocosi** [comment]
Hi there!

Just sent a fix to this issue.

Could you please test again? 

Thank you for the support!
